{% set name = "Beaker" %}
{% set version = "1.13.0" %}
{% set sha256 = "e956cd8a35ad5de1b5212c7bff8fc01e2b3d34ab92466d24684c666abb8c9c30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - beaker
    - beaker.crypto
    - beaker.ext

about:
  home: https://beaker.readthedocs.io/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A Session and Caching library with WSGI Middleware
  description: |
    Beaker is a web session and general caching library that includes WSGI
    middleware for use in web applications.

    As a general caching library, Beaker can handle storing for various times
    any Python object that can be pickled with optional back-ends on a
    fine-grained basis.

    Beaker includes Cache and Session WSGI middleware to ease integration with
    WSGI capable frameworks, and is automatically used by Pylons and
    TurboGears.

  doc_url: http://beaker.groovie.org/
  dev_url: https://github.com/bbangert/beaker

extra:
  recipe-maintainers:
    - stuertz
